// Churn Risk API — predictive churn scoring for Cincinnati pilot demo (30 accounts)

function getAccounts() {
  const now = new Date();
  function daysFromNow(d) { return new Date(now.getTime() + d * 86400000).toISOString().slice(0, 10); }

const ACCOUNTS = [
  // ── CRITICAL ─────────────────────────────────────────────────────────────
  {
    id: 'trihealth-good-sam', name: 'TriHealth Good Samaritan Hospital', industry: 'medical',
    territory: 'Northside / Clifton', contract_value_annual: 78000, churn_probability: 0.71,
    risk_tier: 'critical', days_to_likely_action: 28,
    risk_factors: ['sizing_complaints', 'key_contact_changed', 'missed_delivery'],
    assigned_rsr: 'Sandra K.', contract_renewal_date: daysFromNow(62), contract_age_months: 18,
    complaint_count: 3, last_complaint_days: 2,
    delivery_score: 48, quality_score: 35, relationship_score: 42,
    order_volume_trend: 'declining', order_volume_change_pct: -22,
    last_rsr_contact_days: 14, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: null,
    account_contact_name: 'Kevin Marsh', account_contact_title: 'Operations Director',
    notes: 'Three consecutive weeks of wrong scrub sizes have pushed Kevin Marsh to the edge of formal escalation — a written resolution plan is needed before the next delivery.',
    recommended_action: 'Call Kevin Marsh before route, bring written resolution plan for sizing errors, offer billing credit.',
    recommended_action_deadline: 'this_visit',
  },
  {
    id: 'mason-medical-center', name: 'Mason Medical Center', industry: 'medical',
    territory: 'Blue Ash / Mason', contract_value_annual: 52000, churn_probability: 0.68,
    risk_tier: 'critical', days_to_likely_action: 35,
    risk_factors: ['delivery_delays', 'billing_dispute', 'contract_renewal_approaching'],
    assigned_rsr: 'Carlos P.', contract_renewal_date: daysFromNow(88), contract_age_months: 24,
    complaint_count: 2, last_complaint_days: 4,
    delivery_score: 52, quality_score: 60, relationship_score: 45,
    order_volume_trend: 'stable', order_volume_change_pct: -5,
    last_rsr_contact_days: 8, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: null,
    account_contact_name: 'Ellen Torres', account_contact_title: 'Administrative Director',
    notes: 'Ellen Torres sent a formal email to ops after the second missed pickup — this account requires documented resolution, not verbal assurance.',
    recommended_action: 'Deliver written resolution letter, confirm corrected pickup schedule, offer service credit.',
    recommended_action_deadline: 'this_visit',
  },
  {
    id: 'fc-cincinnati', name: 'FC Cincinnati Training Facility', industry: 'fitness',
    territory: 'Downtown / OTR', contract_value_annual: 64000, churn_probability: 0.61,
    risk_tier: 'critical', days_to_likely_action: 42,
    risk_factors: ['wrong_items', 'competitive_inquiry', 'reduced_order_volume'],
    assigned_rsr: 'Mike T.', contract_renewal_date: daysFromNow(105), contract_age_months: 9,
    complaint_count: 2, last_complaint_days: 3,
    delivery_score: 58, quality_score: 44, relationship_score: 51,
    order_volume_trend: 'declining', order_volume_change_pct: -15,
    last_rsr_contact_days: 5, competitive_signal: true,
    competitive_signal_detail: 'Dana Loftus mentioned Cintas direct pricing in last call',
    upsell_opportunity: 'first_aid',
    account_contact_name: 'Dana Loftus', account_contact_title: 'Operations Manager',
    notes: 'Dana has explicitly mentioned competitor pricing — call before the route visit and lead with a sizing audit offer and service credit to buy loyalty before renewal.',
    recommended_action: 'Call Dana before visit, offer sizing audit and delivery credit, present renewal incentive.',
    recommended_action_deadline: 'this_visit',
  },

  // ── ELEVATED ─────────────────────────────────────────────────────────────
  {
    id: 'university-of-cincinnati', name: 'University of Cincinnati Dining', industry: 'education',
    territory: 'Northside / Clifton', contract_value_annual: 44000, churn_probability: 0.42,
    risk_tier: 'elevated', days_to_likely_action: 72,
    risk_factors: ['contract_renewal_approaching', 'key_contact_changed', 'reduced_order_volume'],
    assigned_rsr: 'Sandra K.', contract_renewal_date: daysFromNow(55), contract_age_months: 14,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 74, quality_score: 78, relationship_score: 52,
    order_volume_trend: 'declining', order_volume_change_pct: -18,
    last_rsr_contact_days: 12, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: 'mats',
    account_contact_name: 'David Lau', account_contact_title: 'Facilities Coordinator',
    notes: 'New facilities coordinator came on board 3 months ago — relationship needs to be rebuilt before the 55-day renewal window closes.',
    recommended_action: 'Schedule in-person meeting with David Lau before renewal window; bring performance report and introduce floor mat program.',
    recommended_action_deadline: 'this_week',
  },
  {
    id: 'procter-gamble-cafeteria', name: "P&G Campus Cafeteria (Mason)", industry: 'other',
    territory: 'Blue Ash / Mason', contract_value_annual: 87000, churn_probability: 0.52,
    risk_tier: 'elevated', days_to_likely_action: 65,
    risk_factors: ['contract_renewal_approaching', 'key_contact_changed'],
    assigned_rsr: 'Carlos P.', contract_renewal_date: daysFromNow(45), contract_age_months: 36,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 82, quality_score: 79, relationship_score: 58,
    order_volume_trend: 'stable', order_volume_change_pct: 2,
    last_rsr_contact_days: 3, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: 'mats',
    account_contact_name: "Don O'Brien", account_contact_title: 'Facilities Manager',
    notes: 'Company-wide vendor audit underway in Q1 — Don mentioned reviewing all service contracts, making proactive outreach and documentation critical before the 45-day renewal.',
    recommended_action: 'Request formal meeting with Don and procurement manager; bring 2-year performance summary.',
    recommended_action_deadline: 'this_week',
  },
  {
    id: 'kenwood-towne-marriott', name: 'Kenwood Towne Courtyard (Marriott)', industry: 'hospitality',
    territory: 'Kenwood / Hyde Park', contract_value_annual: 56000, churn_probability: 0.47,
    risk_tier: 'elevated', days_to_likely_action: 70,
    risk_factors: ['quality_complaints', 'reduced_order_volume'],
    assigned_rsr: 'James R.', contract_renewal_date: daysFromNow(120), contract_age_months: 15,
    complaint_count: 1, last_complaint_days: 7,
    delivery_score: 71, quality_score: 63, relationship_score: 69,
    order_volume_trend: 'declining', order_volume_change_pct: -8,
    last_rsr_contact_days: 7, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: 'restroom',
    account_contact_name: 'Rachel Bloom', account_contact_title: 'General Manager',
    notes: 'GM Rachel Bloom noticed towel pilling in passing — get ahead of it by swapping out old inventory before it becomes a formal complaint.',
    recommended_action: 'Proactively swap oldest towel inventory on next delivery; follow up with Rachel in writing.',
    recommended_action_deadline: 'this_visit',
  },
  {
    id: 'uptown-fitness-clifton', name: 'Uptown Fitness Clifton', industry: 'fitness',
    territory: 'Northside / Clifton', contract_value_annual: 28000, churn_probability: 0.44,
    risk_tier: 'elevated', days_to_likely_action: 75,
    risk_factors: ['reduced_order_volume', 'competitive_inquiry'],
    assigned_rsr: 'Sandra K.', contract_renewal_date: daysFromNow(90), contract_age_months: 12,
    complaint_count: 1, last_complaint_days: 14,
    delivery_score: 78, quality_score: 75, relationship_score: 55,
    order_volume_trend: 'declining', order_volume_change_pct: -15,
    last_rsr_contact_days: 14, competitive_signal: true,
    competitive_signal_detail: 'Chad Evans mentioned looking at local alternatives last month',
    upsell_opportunity: 'first_aid',
    account_contact_name: 'Chad Evans', account_contact_title: 'General Manager',
    notes: 'Order volume has dropped 15% over two months — ask directly about program satisfaction and offer an inventory count review.',
    recommended_action: 'Ask Chad directly about program satisfaction; offer inventory review and loyalty pricing.',
    recommended_action_deadline: 'this_week',
  },
  {
    id: 'orchids-palm-court', name: 'Orchids at Palm Court (Hilton)', industry: 'restaurant',
    territory: 'Downtown / OTR', contract_value_annual: 42000, churn_probability: 0.41,
    risk_tier: 'elevated', days_to_likely_action: 80,
    risk_factors: ['quality_complaints', 'contract_renewal_approaching'],
    assigned_rsr: 'Mike T.', contract_renewal_date: daysFromNow(45), contract_age_months: 22,
    complaint_count: 1, last_complaint_days: 4,
    delivery_score: 73, quality_score: 61, relationship_score: 67,
    order_volume_trend: 'stable', order_volume_change_pct: -3,
    last_rsr_contact_days: 4, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: null,
    account_contact_name: 'Adriana Reyes', account_contact_title: 'Executive Chef',
    notes: 'An unresolved linen quality complaint with contract renewal in 45 days is a dangerous combination — bring replacement linens and close this formally today.',
    recommended_action: 'Bring replacement linens, issue formal complaint resolution, initiate early renewal conversation.',
    recommended_action_deadline: 'this_visit',
  },
  {
    id: 'hyde-park-grille', name: 'Hyde Park Grille', industry: 'restaurant',
    territory: 'Kenwood / Hyde Park', contract_value_annual: 38000, churn_probability: 0.35,
    risk_tier: 'elevated', days_to_likely_action: 85,
    risk_factors: ['billing_dispute', 'reduced_order_volume'],
    assigned_rsr: 'James R.', contract_renewal_date: daysFromNow(130), contract_age_months: 28,
    complaint_count: 1, last_complaint_days: 18,
    delivery_score: 77, quality_score: 72, relationship_score: 49,
    order_volume_trend: 'declining', order_volume_change_pct: -20,
    last_rsr_contact_days: 10, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: null,
    account_contact_name: 'Mike Donovan', account_contact_title: 'Owner',
    notes: 'Owner Mike Donovan reduced linen orders 20% after an uncorrected billing error — in-person apology and corrected invoice are essential for recovery.',
    recommended_action: 'Bring corrected invoice and goodwill credit in person; owner responds to face-to-face accountability.',
    recommended_action_deadline: 'this_week',
  },
  {
    id: 'yoga-district-clifton', name: 'Yoga District Clifton', industry: 'fitness',
    territory: 'Northside / Clifton', contract_value_annual: 14000, churn_probability: 0.38,
    risk_tier: 'elevated', days_to_likely_action: 60,
    risk_factors: ['competitive_inquiry', 'pricing_sensitivity'],
    assigned_rsr: 'Sandra K.', contract_renewal_date: daysFromNow(30), contract_age_months: 8,
    complaint_count: 1, last_complaint_days: 30,
    delivery_score: 81, quality_score: 78, relationship_score: 61,
    order_volume_trend: 'stable', order_volume_change_pct: 0,
    last_rsr_contact_days: 30, competitive_signal: true,
    competitive_signal_detail: 'Sasha Park mentioned a Cintas competitor quote last visit',
    upsell_opportunity: 'mats',
    account_contact_name: 'Sasha Park', account_contact_title: 'Studio Owner',
    notes: 'Renewal in 30 days and a competitor quote on the table — proactively offer a 2-year loyalty rate lock before she asks.',
    recommended_action: 'Offer 2-year loyalty rate lock before Sasha raises the competitor quote.',
    recommended_action_deadline: 'this_week',
  },
  {
    id: 'summit-hotel-blue-ash', name: 'The Summit Hotel (Blue Ash)', industry: 'hospitality',
    territory: 'Blue Ash / Mason', contract_value_annual: 48000, churn_probability: 0.34,
    risk_tier: 'elevated', days_to_likely_action: 90,
    risk_factors: ['billing_dispute', 'contract_renewal_approaching'],
    assigned_rsr: 'Carlos P.', contract_renewal_date: daysFromNow(75), contract_age_months: 30,
    complaint_count: 1, last_complaint_days: 21,
    delivery_score: 83, quality_score: 80, relationship_score: 64,
    order_volume_trend: 'stable', order_volume_change_pct: 1,
    last_rsr_contact_days: 21, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: null,
    account_contact_name: 'Carol Webb', account_contact_title: 'Housekeeping Director',
    notes: 'A billing discrepancy from November remains open after 3 weeks — Carol is tracking it and trust is eroding; close this before the 75-day renewal window.',
    recommended_action: 'Bring corrected invoice and offer credit for the delay; document resolution in writing.',
    recommended_action_deadline: 'this_visit',
  },

  // ── MONITOR ──────────────────────────────────────────────────────────────
  {
    id: 'kroger-hq-cafe', name: 'Kroger HQ Campus Cafeteria', industry: 'other',
    territory: 'Downtown / OTR', contract_value_annual: 62000, churn_probability: 0.28,
    risk_tier: 'monitor', days_to_likely_action: 120,
    risk_factors: ['delivery_delays'],
    assigned_rsr: 'Mike T.', contract_renewal_date: daysFromNow(180), contract_age_months: 48,
    complaint_count: 1, last_complaint_days: 10,
    delivery_score: 72, quality_score: 81, relationship_score: 74,
    order_volume_trend: 'stable', order_volume_change_pct: 3,
    last_rsr_contact_days: 10, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: 'mats',
    account_contact_name: 'Marcus Webb', account_contact_title: 'Facilities Manager',
    notes: 'A delivery timing complaint 10 days ago has gone without RSR follow-up — unaddressed complaints compound quickly with corporate accounts.',
    recommended_action: 'Proactive check-in with Marcus; document the follow-up to show responsiveness.',
    recommended_action_deadline: 'this_week',
  },
  {
    id: 'fifth-third-arena-catering', name: 'Fifth Third Arena (Catering Ops)', industry: 'other',
    territory: 'Downtown / OTR', contract_value_annual: 95000, churn_probability: 0.22,
    risk_tier: 'monitor', days_to_likely_action: 150,
    risk_factors: ['key_contact_changed'],
    assigned_rsr: 'Mike T.', contract_renewal_date: daysFromNow(200), contract_age_months: 60,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 88, quality_score: 86, relationship_score: 62,
    order_volume_trend: 'growing', order_volume_change_pct: 8,
    last_rsr_contact_days: 3, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: 'fire_protection',
    account_contact_name: 'Ray Dominguez', account_contact_title: 'Catering Director',
    notes: 'New catering director is still in relationship-building mode — use this quarter to establish trust before event season ramps up.',
    recommended_action: 'Schedule introductory lunch with Ray Dominguez; propose fire protection add-on.',
    recommended_action_deadline: 'this_month',
  },
  {
    id: 'uc-health-univ-hospital', name: 'UC Health University Hospital', industry: 'medical',
    territory: 'Northside / Clifton', contract_value_annual: 145000, churn_probability: 0.18,
    risk_tier: 'monitor', days_to_likely_action: 180,
    risk_factors: ['contract_renewal_approaching'],
    assigned_rsr: 'Sandra K.', contract_renewal_date: daysFromNow(120), contract_age_months: 84,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 91, quality_score: 88, relationship_score: 78,
    order_volume_trend: 'stable', order_volume_change_pct: 4,
    last_rsr_contact_days: 2, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: null,
    account_contact_name: 'Maria L.', account_contact_title: 'Supply Chain Manager',
    notes: 'Longest-tenured large account on the roster — renewal in 120 days warrants a formal review meeting with Maria and senior supply chain leadership.',
    recommended_action: 'Schedule formal renewal review meeting with supply chain leadership 90 days before expiry.',
    recommended_action_deadline: 'this_month',
  },
  {
    id: 'xavier-university', name: 'Xavier University', industry: 'education',
    territory: 'Northside / Clifton', contract_value_annual: 36000, churn_probability: 0.24,
    risk_tier: 'monitor', days_to_likely_action: 160,
    risk_factors: ['reduced_order_volume', 'pricing_sensitivity'],
    assigned_rsr: 'Sandra K.', contract_renewal_date: daysFromNow(140), contract_age_months: 20,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 84, quality_score: 82, relationship_score: 70,
    order_volume_trend: 'declining', order_volume_change_pct: -10,
    last_rsr_contact_days: 8, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: 'mats',
    account_contact_name: 'Patricia Coen', account_contact_title: 'Facilities Director',
    notes: 'Summer enrollment dips cause predictable volume reduction — educate the facilities director on how to right-size the program rather than cut services.',
    recommended_action: 'Present seasonal volume adjustment plan; introduce floor mat program for common areas.',
    recommended_action_deadline: 'this_month',
  },
  {
    id: 'anderson-township-medical', name: 'Anderson Township Medical Group', industry: 'medical',
    territory: 'Blue Ash / Mason', contract_value_annual: 31000, churn_probability: 0.15,
    risk_tier: 'monitor', days_to_likely_action: 200,
    risk_factors: ['reduced_order_volume'],
    assigned_rsr: 'Carlos P.', contract_renewal_date: daysFromNow(150), contract_age_months: 36,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 87, quality_score: 85, relationship_score: 80,
    order_volume_trend: 'declining', order_volume_change_pct: -7,
    last_rsr_contact_days: 5, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: null,
    account_contact_name: 'Lisa Barr', account_contact_title: 'Office Manager',
    notes: 'Order volume has declined modestly — a simple count audit with Lisa could surface unmet needs and shore up the relationship before renewal.',
    recommended_action: 'Offer a complimentary inventory count audit; confirm all service categories are being used.',
    recommended_action_deadline: 'this_month',
  },
  {
    id: 'cincinnati-state-tech', name: 'Cincinnati State Technical College', industry: 'education',
    territory: 'Northside / Clifton', contract_value_annual: 29000, churn_probability: 0.13,
    risk_tier: 'monitor', days_to_likely_action: 210,
    risk_factors: ['contract_renewal_approaching'],
    assigned_rsr: 'Sandra K.', contract_renewal_date: daysFromNow(160), contract_age_months: 10,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 88, quality_score: 86, relationship_score: 72,
    order_volume_trend: 'stable', order_volume_change_pct: 2,
    last_rsr_contact_days: 7, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: 'first_aid',
    account_contact_name: 'Tom Neff', account_contact_title: 'Facilities Coordinator',
    notes: 'Newer account showing stable volume and no complaints — build the relationship now to ensure a smooth first renewal and introduce first aid cabinets.',
    recommended_action: 'Schedule a relationship check-in with Tom Neff; propose first aid cabinet program for campus.',
    recommended_action_deadline: 'this_month',
  },
  {
    id: 'kenwood-country-club', name: 'Kenwood Country Club', industry: 'hospitality',
    territory: 'Kenwood / Hyde Park', contract_value_annual: 41000, churn_probability: 0.19,
    risk_tier: 'monitor', days_to_likely_action: 190,
    risk_factors: ['key_contact_changed'],
    assigned_rsr: 'James R.', contract_renewal_date: daysFromNow(170), contract_age_months: 44,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 85, quality_score: 83, relationship_score: 65,
    order_volume_trend: 'stable', order_volume_change_pct: 5,
    last_rsr_contact_days: 6, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: null,
    account_contact_name: 'Claire Hamilton', account_contact_title: 'Club Manager',
    notes: 'New club manager came on board 2 months ago — schedule an introduction visit before the seasonal volume ramp in spring.',
    recommended_action: 'Schedule in-person introduction with Claire Hamilton; discuss spring volume forecast.',
    recommended_action_deadline: 'this_month',
  },
  {
    id: 'blue-ash-surgery-ctr', name: 'Blue Ash Surgery Center', industry: 'medical',
    territory: 'Blue Ash / Mason', contract_value_annual: 58000, churn_probability: 0.10,
    risk_tier: 'monitor', days_to_likely_action: 220,
    risk_factors: ['reduced_order_volume'],
    assigned_rsr: 'Carlos P.', contract_renewal_date: daysFromNow(195), contract_age_months: 42,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 92, quality_score: 90, relationship_score: 82,
    order_volume_trend: 'declining', order_volume_change_pct: -6,
    last_rsr_contact_days: 4, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: null,
    account_contact_name: 'Patricia Moore', account_contact_title: 'OR Coordinator',
    notes: 'A small volume decline may reflect scheduling changes rather than dissatisfaction — verify with Patricia before the pattern becomes a concern.',
    recommended_action: 'Confirm volume decline with Patricia Moore; verify surgical schedule changes vs. service issue.',
    recommended_action_deadline: 'this_month',
  },

  // ── HEALTHY ──────────────────────────────────────────────────────────────
  {
    id: 'marriott-rivercenter', name: 'Marriott at RiverCenter', industry: 'hospitality',
    territory: 'Blue Ash / Mason', contract_value_annual: 112000, churn_probability: 0.08,
    risk_tier: 'healthy', days_to_likely_action: null,
    risk_factors: [],
    assigned_rsr: 'Carlos P.', contract_renewal_date: daysFromNow(240), contract_age_months: 72,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 96, quality_score: 95, relationship_score: 94,
    order_volume_trend: 'growing', order_volume_change_pct: 6,
    last_rsr_contact_days: 1, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: null,
    account_contact_name: 'Tom Halloran', account_contact_title: 'Director of Housekeeping',
    notes: 'Renewed 2-year contract without negotiation — Tom Halloran cited consistent 6am delivery as the deciding factor; maintain this standard.',
    recommended_action: 'Ask Tom for a referral to Marriott regional contacts; introduce fire protection services.',
    recommended_action_deadline: 'this_month',
  },
  {
    id: 'skyline-chili-corp', name: 'Skyline Chili (Corporate)', industry: 'restaurant',
    territory: 'Blue Ash / Mason', contract_value_annual: 89000, churn_probability: 0.07,
    risk_tier: 'healthy', days_to_likely_action: null,
    risk_factors: [],
    assigned_rsr: 'Carlos P.', contract_renewal_date: daysFromNow(300), contract_age_months: 96,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 93, quality_score: 91, relationship_score: 92,
    order_volume_trend: 'stable', order_volume_change_pct: 2,
    last_rsr_contact_days: 1, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: null,
    account_contact_name: 'Brian Kim', account_contact_title: 'Corporate Operations',
    notes: 'Longest-tenured restaurant account on the roster — covers 7 locations under a single invoice with Brian Kim as a reliable point of contact.',
    recommended_action: 'Pitch fire protection services across corporate locations on next quarterly call.',
    recommended_action_deadline: 'this_month',
  },
  {
    id: 'cincinnati-childrens', name: "Cincinnati Children's Hospital", industry: 'medical',
    territory: 'Northside / Clifton', contract_value_annual: 128000, churn_probability: 0.06,
    risk_tier: 'healthy', days_to_likely_action: null,
    risk_factors: [],
    assigned_rsr: 'Sandra K.', contract_renewal_date: daysFromNow(365), contract_age_months: 108,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 99, quality_score: 98, relationship_score: 97,
    order_volume_trend: 'stable', order_volume_change_pct: 3,
    last_rsr_contact_days: 1, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: null,
    account_contact_name: 'Rita Okafor', account_contact_title: 'Materials Management',
    notes: 'Rita Okafor sent a formal commendation after 12 consecutive perfect delivery months — this is the benchmark relationship on the roster.',
    recommended_action: 'Request a case study or testimonial from Rita; use as reference for pediatric hospital prospects.',
    recommended_action_deadline: 'this_month',
  },
  {
    id: 'precinct-restaurant', name: 'The Precinct', industry: 'restaurant',
    territory: 'Downtown / OTR', contract_value_annual: 54000, churn_probability: 0.05,
    risk_tier: 'healthy', days_to_likely_action: null,
    risk_factors: [],
    assigned_rsr: 'Mike T.', contract_renewal_date: daysFromNow(270), contract_age_months: 48,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 95, quality_score: 94, relationship_score: 93,
    order_volume_trend: 'growing', order_volume_change_pct: 5,
    last_rsr_contact_days: 2, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: null,
    account_contact_name: 'Tom Brennan', account_contact_title: 'General Manager',
    notes: 'Tom Brennan referred a new restaurant prospect last week — the relationship is strong enough for formal referral conversations.',
    recommended_action: 'Follow up on the referred prospect; ask Tom for an introduction to Precinct ownership group.',
    recommended_action_deadline: 'this_month',
  },
  {
    id: 'blue-ash-sports-center', name: 'Blue Ash Sports Center', industry: 'fitness',
    territory: 'Blue Ash / Mason', contract_value_annual: 37000, churn_probability: 0.09,
    risk_tier: 'healthy', days_to_likely_action: null,
    risk_factors: [],
    assigned_rsr: 'Carlos P.', contract_renewal_date: daysFromNow(220), contract_age_months: 24,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 90, quality_score: 89, relationship_score: 86,
    order_volume_trend: 'growing', order_volume_change_pct: 12,
    last_rsr_contact_days: 3, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: 'first_aid',
    account_contact_name: 'Amanda Nguyen', account_contact_title: 'Operations Manager',
    notes: 'Volume is growing with the Jan-Feb seasonal spike — a first aid cabinet add-on is an easy conversation given the sports facility context.',
    recommended_action: 'Pitch first aid cabinets during seasonal volume review; document upsell in CRM.',
    recommended_action_deadline: 'this_month',
  },
  {
    id: 'tafts-ale-house', name: "Taft's Ale House", industry: 'restaurant',
    territory: 'Downtown / OTR', contract_value_annual: 22000, churn_probability: 0.06,
    risk_tier: 'healthy', days_to_likely_action: null,
    risk_factors: [],
    assigned_rsr: 'Mike T.', contract_renewal_date: daysFromNow(190), contract_age_months: 18,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 91, quality_score: 90, relationship_score: 88,
    order_volume_trend: 'stable', order_volume_change_pct: 4,
    last_rsr_contact_days: 2, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: 'mats',
    account_contact_name: 'Kris Miller', account_contact_title: 'Owner',
    notes: 'Kris Miller has asked about floor mats twice in the last 3 months — the pitch is ready, close it on this visit.',
    recommended_action: "Close the floor mat upsell — Kris has asked twice, don't wait for a third.",
    recommended_action_deadline: 'this_visit',
  },
  {
    id: '21c-museum-hotel', name: '21c Museum Hotel', industry: 'hospitality',
    territory: 'Downtown / OTR', contract_value_annual: 48000, churn_probability: 0.07,
    risk_tier: 'healthy', days_to_likely_action: null,
    risk_factors: [],
    assigned_rsr: 'Mike T.', contract_renewal_date: daysFromNow(260), contract_age_months: 30,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 94, quality_score: 93, relationship_score: 89,
    order_volume_trend: 'stable', order_volume_change_pct: 3,
    last_rsr_contact_days: 2, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: 'restroom',
    account_contact_name: 'Priya Sharma', account_contact_title: 'Director of Operations',
    notes: 'Boutique property where quality is everything — Priya values the 7am guarantee and would respond well to a premium restroom supply program.',
    recommended_action: 'Propose premium restroom supply program during next delivery check-in with Priya.',
    recommended_action_deadline: 'this_month',
  },
  {
    id: 'otr-brewing', name: 'OTR Brewing Company', industry: 'restaurant',
    territory: 'Downtown / OTR', contract_value_annual: 18000, churn_probability: 0.09,
    risk_tier: 'healthy', days_to_likely_action: null,
    risk_factors: [],
    assigned_rsr: 'Mike T.', contract_renewal_date: daysFromNow(185), contract_age_months: 16,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 88, quality_score: 87, relationship_score: 83,
    order_volume_trend: 'growing', order_volume_change_pct: 15,
    last_rsr_contact_days: 4, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: null,
    account_contact_name: 'Sam Ortega', account_contact_title: 'Operations Manager',
    notes: 'Growing account with strong volume trend — Sam is receptive and this is a good candidate for a restroom supply add-on.',
    recommended_action: 'Pitch restroom supply program to Sam; growth trajectory makes this an easy conversation.',
    recommended_action_deadline: 'this_month',
  },
  {
    id: 'blue-ash-brewing', name: 'Blue Ash Brewing Company', industry: 'restaurant',
    territory: 'Blue Ash / Mason', contract_value_annual: 20000, churn_probability: 0.06,
    risk_tier: 'healthy', days_to_likely_action: null,
    risk_factors: [],
    assigned_rsr: 'Carlos P.', contract_renewal_date: daysFromNow(195), contract_age_months: 22,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 90, quality_score: 89, relationship_score: 91,
    order_volume_trend: 'stable', order_volume_change_pct: 3,
    last_rsr_contact_days: 3, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: 'mats',
    account_contact_name: 'Mike Frazier', account_contact_title: 'Owner',
    notes: 'Mike Frazier has asked about floor mats twice — close the upsell today while interest is high.',
    recommended_action: 'Close floor mat upsell with Mike — he has asked twice, this is a warm pitch.',
    recommended_action_deadline: 'this_visit',
  },
  {
    id: 'rookwood-pottery-rest', name: 'Rookwood Pottery Restaurant', industry: 'restaurant',
    territory: 'Kenwood / Hyde Park', contract_value_annual: 24000, churn_probability: 0.05,
    risk_tier: 'healthy', days_to_likely_action: null,
    risk_factors: [],
    assigned_rsr: 'James R.', contract_renewal_date: daysFromNow(280), contract_age_months: 12,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 92, quality_score: 91, relationship_score: 90,
    order_volume_trend: 'growing', order_volume_change_pct: 10,
    last_rsr_contact_days: 2, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: null,
    account_contact_name: 'Terrence Wade', account_contact_title: 'General Manager',
    notes: 'Floor mat program added this year — $8,400 incremental revenue — relationship is strong and Terrence is open to further upsell conversations.',
    recommended_action: 'Offer restroom supply or first aid add-on on next visit; Terrence is an easy upsell target.',
    recommended_action_deadline: 'this_month',
  },
  {
    id: 'clifton-heights-rehab', name: 'Clifton Heights Physical Therapy', industry: 'medical',
    territory: 'Northside / Clifton', contract_value_annual: 15000, churn_probability: 0.11,
    risk_tier: 'healthy', days_to_likely_action: null,
    risk_factors: [],
    assigned_rsr: 'Sandra K.', contract_renewal_date: daysFromNow(230), contract_age_months: 38,
    complaint_count: 0, last_complaint_days: null,
    delivery_score: 88, quality_score: 87, relationship_score: 85,
    order_volume_trend: 'stable', order_volume_change_pct: 1,
    last_rsr_contact_days: 5, competitive_signal: false, competitive_signal_detail: null,
    upsell_opportunity: 'first_aid',
    account_contact_name: 'Dr. Michael Cho', account_contact_title: 'Practice Owner',
    notes: 'Long-term account with consistent payment history — first aid cabinets are a natural fit for a physical therapy clinic.',
    recommended_action: 'Propose first aid cabinet program to Dr. Cho; clinical setting makes this a compelling fit.',
    recommended_action_deadline: 'this_month',
  },
];
  return ACCOUNTS;
}

function computeSummary(accounts) {
  const criticalAccounts = accounts.filter(a => a.risk_tier === 'critical');
  const elevatedAccounts = accounts.filter(a => a.risk_tier === 'elevated');
  const revenueAtRisk = criticalAccounts.reduce((sum, a) => sum + a.contract_value_annual, 0) +
    elevatedAccounts.reduce((sum, a) => sum + (a.contract_value_annual * 0.5), 0);
  const saveable = Math.round(revenueAtRisk * 0.5);
  const upsellCount = accounts.filter(a => a.upsell_opportunity).length;

  return {
    total_accounts: accounts.length,
    critical_accounts: criticalAccounts.length,
    elevated_accounts: elevatedAccounts.length,
    monitor_accounts: accounts.filter(a => a.risk_tier === 'monitor').length,
    healthy_accounts: accounts.filter(a => a.risk_tier === 'healthy').length,
    total_revenue_at_risk: Math.round(revenueAtRisk),
    revenue_saveable_with_intervention: saveable,
    avg_churn_probability: parseFloat((accounts.reduce((s, a) => s + a.churn_probability, 0) / accounts.length).toFixed(3)),
    avg_days_to_complaint_response_branch: 3.8,
    upsell_opportunities_total: upsellCount,
    upsell_revenue_potential: 127000,
  };
}

export async function onRequestGet(context) {
  const { request } = context;
  const url = new URL(request.url);
  const tierFilter = url.searchParams.get('tier');
  const headers = { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' };

  try {
    const ACCOUNTS = getAccounts();
    const sorted = [...ACCOUNTS].sort((a, b) => b.churn_probability - a.churn_probability);
    const filtered = tierFilter ? sorted.filter(a => a.risk_tier === tierFilter) : sorted;

    return new Response(JSON.stringify({
      accounts: filtered,
      branch_summary: computeSummary(ACCOUNTS),
      generated_at: new Date().toISOString(),
      pilot: 'Cincinnati — 90-Day Pilot Demo',
    }), { headers });
  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), { status: 500, headers });
  }
}

export async function onRequestOptions() {
  return new Response(null, { headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET,OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type' } });
}
